### ISSUE TITLE
Fossil: no such file: <relative path to untracked file>

### ISSUE THREAD

**Issue by vor0nwe** [koog1000/vscode-fossil#13]
Since version 0.0.11 of the plugin, I keep getting pop-ups saying `Fossil: no such file: ...` with the relative path and filename of the file I'm currently editing. This is a file that I haven’t added to the repository yet:
![image](https://user-images.githubusercontent.com/76925/66287390-e63dd200-e8d5-11e9-9420-a7d8edb6b0e8.png)

Coincidentally, the error popup sports an 'Open Fossil Log' button, but that doesn't do anything.
Manually opening the 'Fossil' output window, I see it tries to do [`fossil cat <path-and-filename>`](https://www.fossil-scm.org/fossil/help?cmd=cat), which fails — understandably, since the file hasn't been added to the repository yet.

While this is annoying, it wouldn't be a problem if it didn't stop the entire plugin from working; the version control panel now remains completely empty.

Going back to version 0.0.10 of the plugin fixes these problems.

**Comment by koog1000** [comment]
I didn't notice that on my machine. If it's what I think it is then it should be a quick fix.

**Comment by koog1000** [comment]
Latest release should fix it, [609cb5c6681eaf3728d1e65524bdf160bcdaa8ae]

I appreciate you for letting me know about these issues, keep them coming.

More details:
The error prompt that I added in v0.0.11 was defaulted to prompt on any error, but this causes problems because the fossil extension is used at times that it is guaranteed to fail, which I didn't run into in my *limited* testing. 
The case you saw is because Fossil is registered as a quickdiffeditor and VSCode will request diff information on open files. It will do this regardless of whether or not the file is part of the fossil repo. Another case is if you open VSCode in a directory that is not a fossil checkout then you will get errors about not being in a valid checkout. 
As a fix I just filter on the error type and only display the error prompt if it is not an expected error case. Oh, and I fixed the 'Open Fossil Log' button to actually open the log.

**Comment by vor0nwe** [comment]
Thanks a lot for your speedy fix!

A few observations:
* I now get (quite a few) error popups of `Fossil: use --repository or -R to specify the repository database`. Maybe those should get recognized as well.
* The Fossil log now opens without me having to click `Open Fossil Log` at all. But closing the lower panel (which includes the output window), then clicking the `Open Fossil Log` button, doesn’t reopen the fossil output panel.
* The problem where the source control panel remains empty is still there, but that might be related to something else: I had added a virtual folder (an [SSH FS](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) folder) to that specific workspace, and that seems to be what 0.0.11 (and 0.0.12) trip over; though 0.0.10 has no problems with that configuration. A different workspace, with a single (local) root, works fine — though it also triggers the abovementioned error popup.

I’m off to work now, and will likely be offline the rest of this week. I’ll see when I can do more tests to narrow down what goes wrong in which situations, but that probably won't be earlier than the weekend after next. I will create separate issues once I've isolated the problems.

**Comment by koog1000** [comment]
Yes, I was seeing the `Fossil: use --repository or -R to specify the repository database` as well, but it went away when I filtered the other errors. Looking into it more, this error is thrown by [`fossil cat`](https://www.fossil-scm.org/home/help?cmd=cat) when fossil cannot find a valid checkout. 

So this should be added to the filter list for the case where VSCode is in fact not in an open checkout, but I'm curious if that was your situation. When you were receiving this error were you in a valid fossil checkout? I'm thinking it may have something to do with the SSH FS and there actually could be a problem with the extension not working correctly. Is fossil installed on the machine you are SSHing into?
