### ISSUE TITLE
Untracked Files should exclude clean-glob

### ISSUE THREAD

**Issue by t-voet** [koog1000/vscode-fossil#162]
### Desire

5

### Help

- [X] Discuss
- [X] Test
- [ ] Code

### Description

_Untracked Files_ should exclude `clean-glob`, in addition to `ignore-glob`.
This is the default behavior of Fossil, eg. `fossil addremove`.
[https://fossil-scm.org/home/help?cmd=clean-glob](url)

**Comment by senyai** [comment]
Hi. This extension isn't doing anything fancy to list the untracked files. It just reads output of `fossil status --differ --merge`. So the whole burden of whether a path is going to be treated as untracked lies on fossil developers. Looking at fossil source code, I can tell `status` command only ignores `ignore-glob`. And I'm not fancy to read and combine `clean-glob` and `ignore-glob` to pass it to `fossil status`.

I'm not sure what to do. Maybe ask fossil devs to do something, they should know better. I personally never used `clean-glob` because all my output goes to 'build' directory and 'build' directory is in `ignore-glob`.

**Comment by t-voet** [comment]
Thanks! I verified that Fossil is not consistent regarding `clean-glob`. Workarounds are easy enough: include your `clean-glob` in your `ignore-glob` or put this type of files outside your repository. I agree this issue is better tackled elsewhere.

**Comment by senyai** [comment]
I could add VSCode settings to pass `--ignore <CSG>` to `fossil status`, but this would create more issues than it would solve.

**Comment by t-voet** [comment]
I concur. Best to leave the behavior as-is, in accordance with Fossil.
Thanks for your time and I wish you a happy 2024!
